#!/bin/bash -efu

av0dir=
hlsdirs=()
argv=("$@")

for (( i = 1; i < $#; i++ )); do
	[[ ${argv[i-1]} = -i && ${argv[i]} = http://* ]] || continue
	if [ -z "$av0dir" ]; then
		av0=$(readlink -ev "$0")
		av0dir=$(dirname "$av0")
	fi
	argv[i]=$("$av0dir"/wget-hls "${argv[i]}")
	hlsdirs+=("${argv[i]%/*}")
done

if [ "$*" = "${argv[*]-}" ]; then
	exec ffmpeg "$@"
fi

rc=
ffmpeg "${argv[@]}" || rc=$?

[ -n "$rc" ] ||
rm -r "${hlsdirs[@]}"

exit $rc
